# Generated by Django 2.2 on 2019-10-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_num', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('phone_num', models.CharField(blank=True, max_length=10)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_no', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=24)),
                ('dept_no', models.CharField(max_length=4)),
                ('proj_st_date', models.DateField()),
                ('proj_en_date', models.DateField()),
                ('maj_proj', models.CharField(max_length=8)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Empolyee_to_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_no', models.CharField(max_length=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
    ]
