# Generated by Django 2.2 on 2019-10-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='maj_proj',
        ),
    ]
