# Generated by Django 2.2 on 2019-10-08 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_project_maj_proj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empolyee_to_project',
            name='project_no',
        ),
        migrations.AddField(
            model_name='empolyee_to_project',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
            preserve_default=False,
        ),
    ]
